baseURL = 'https://nostuff.org/'
languageCode = 'en-gb'
title = 'nostuff.org | Chris Keene'
theme = 'ananke'
sectionPagesMenu = 'main'
disable_share = 'true'

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[params.ananke_socials]]
  name = 'bluesky'
    lab = 'bluesky'
    url = 'https://bsky.app/profile/chriskeene.bsky.social'

    [[ananke.social.bluesky]]
      username = "chriskeene.bsky.social"
      profilelink = "https://bsky.app/profile/chriskeene.bsky.social"
  
