baseURL = 'https://nostuff.org/'
languageCode = 'en-us'
title = 'nostuff.org | Chris Keene'
theme = 'ananke'
sectionPagesMenu = 'main'

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[params.ananke_socials]]
  disable_share = 'true'
